name: Super-Linter           # Workflow name shown in Actions tab

on:                         # When to run the action
  push:                    # Run on push
    branches:
      - main               # main branch
  pull_request:            # Run on pull requests targeting main

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest # Using GitHub-hosted Linux runner

    permissions:
      contents: read      # Permissions needed for repo access
      statuses: write     # Permissions for reporting back status

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Checks out your repository code

      - name: Run Super-Linter
        uses: github/super-linter@v5 # Runs GitHub's Super-Linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token for access
          DEFAULT_BRANCH: main                     # Default branch
          # Optionally, disable natural language validation for text files
          VALIDATE_NATURAL_LANGUAGE: false
